apiVersion: apps/v1
kind: Deployment
metadata:
  name: medrec-deploy
  
spec:
  replicas: 1
  selector:
    matchLabels:
      app: medrec
  template:
    metadata:
      labels:
        app: medrec
    spec:
      containers:
      - name: medrec-server
        image: cpruvost/12213-wls-medrec-if:latest
        ports:
        - name: medrec-port
          containerPort: 7001
          protocol: TCP
